server:
  port: 8081

#person:
#  name: zhangsan
#  age: 18
#  boss: false
#  birthday: 2020/03/04
#  maps: {k1: v1, k2: v2}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: xiaogou
#    age: 3


